spring.application.name=electronic_bulletin_board
spring.datasource.url=jdbc:mysql://localhost:3306/electronic_bulletin_board
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.rambler.ru
spring.mail.port=587
spring.mail.username=louisecaezgf0@rambler.ru
spring.mail.password=wvmtxkzmS!1805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=7A25432A462D4A614E645267556B58703273357638792F423F4528482B4D6251
jwt.expiration=86400000

spring.security.oauth2.client.registration.github.client-id=Ov23liZL8g5xmGUZ8K0Q
spring.security.oauth2.client.registration.github.client-secret=26bf1648cd9f5c2438eb41a9cf66d32a165a2d09
spring.security.oauth2.client.registration.github.scope=user:email